### ISSUE TITLE
cross compilation of 1.9 release is broken

### ISSUE THREAD

**Issue by rofl0r** [royhills/arp-scan#11]
```
checking whether long int is 64 bits... no                                      
checking whether long long int is 64 bits... yes                                
checking snprintf format for long long int... cannot test (not on host machine) 
configure: error: cannot determine snprintf format string for long long int     
```
the test is not even necessary, the format for long long int is always "%lld"

**Comment by royhills** [comment]
I think the latest git commit should fix this problem.  It assumes that the long long int format is %lld if cross compiling instead of just giving up.

I'm not sure this is very robust, but it's better than just giving up, and %lld will normally work.

Here's an example cross-compiling for i386 on an amd64 debian system:

rsh@jessie:~/arp-scan$ ./configure --build=x86_64-unknown-linux-gnu --host=i686-unknown-linux-gnu "CFLAGS=-m32" "CXXFLAGS=-m32" "LDFLAGS=-m32"
checking for a BSD-compatible install... /usr/bin/install -c
...
checking whether long int is 64 bits... no
checking whether long long int is 64 bits... yes
checking snprintf format for long long int... assuming %lld for cross compilation

**Comment by rofl0r** [comment]
thanks.
do you know any platform where the format is not `%lld`, contrary to the C and POSIX specs ?

**Comment by royhills** [comment]
On 64-bit systems, long int is usually 64-bit, so %ld would be the correct format there and %lld might give a warning.

BSD systems used to use %qd for "quad int" which was 64-bit.  I think that was a while ago though, and may be depreciated.

%I64d is sometimes seen on Microsoft systems, but they may also support %lld as well.

**Comment by royhills** [comment]
I believe this is fixed now.

Defaulting to %lld seems like a bit of a hack, so some cross-compilation builds may still have errors.  But it's certainly better than failing altogether.
