### ISSUE TITLE
reduce size by using search.h for hashtable.

### ISSUE THREAD

**Issue by nihilus** [royhills/arp-scan#15]
For embedded Linux where space is a constraint it would be good if the hashtable used standard <search.h> hashtable functions.

**Comment by nihilus** [comment]
Also by commenting out the usage I was able to reduce the binary by 20 KB!

**Comment by nihilus** [comment]
Something like this: https://gist.github.com/cirocosta/e61e52cc6afe2633500b

**Comment by nihilus** [comment]
I did fix some stuff over at https://github.com/royhills/arp-scan

**Comment by nihilus** [comment]
You can easily look at the changes related to the hashmap. However I am not sur how this handles dupes.

**Comment by royhills** [comment]
I'll look at using the hcreate(), hsearch() and hdestroy() posix functions instead of the hash table implementation that I borrowed from gas.  The main thing I need to check is that these functions are available on all platforms that arp-scan is used on.  That is basically the various flavours of Linux and BSD, as Solaris is not used as much as it used to be.

I'm interested in the reasons behind the changes you've made.  I see that you've slimmed things down a lot - is this to reduce the memory footprint of the resulting executable?

**Comment by nihilus** [comment]
@royhills yeah, a footprint of 350kb w statically linked aginst plain libpcap is undesirable on the embedded Linux system so I figured out I better forked it off and tailored it after my needs.

Contrary to the reenttrant hashmap functions (e.g. hsearch_r()) my changes were made to work on OS X.

**Comment by royhills** [comment]
I've implemented your suggestion, and it seems to work fine: it builds and passes checks on Linux (Debian Jessie), FreeBSD 10.2 and Solaris 10 u11, all on x86_64 architecture.  I'll check out the other popular systems when I get time.

If you know you'll always be running on Linux, and never BSD or Solaris, you could reduce your footprint a bit by removing link-bpf and link-dlpi and just keeping link-packet-socket.  You could also remove the configure.ac logic that chooses between the various link layer implementations to obtain the MAC address.

**Comment by royhills** [comment]
The new version also works on FreeBSD 9.3, NetBSD 6.0.1 and NetBSD 7.0.1.  So I suspect it's pretty portable.  I'm closing this issue now, as I believe it is resolved.
