### ISSUE TITLE
arp table doesn't get populated when using arp-scan

### ISSUE THREAD

**Issue by dsolstad** [royhills/arp-scan#33]
Running arp -a doesn't show any of the discovered hosts from the arp-scan. Is there an option to make this happen?

**Comment by royhills** [comment]
That is the expected behaviour.  arp-scan will report the responding hosts, but will not add them to the OS kernel's ARP table, which is what arp -a uses to display the arp entries.

I'm not planning to change arp-scan to add the responding entries to the kernel table, so this is a wontfix I'm afraid.
