### ISSUE TITLE
please consider a new git tag / release

### ISSUE THREAD

**Issue by anthraxx** [royhills/arp-scan#41]
Hey, It would be awesome to get a new release. Not too much has happened in the meanwhile but some small fixes and improvements plus the use after free bug etc.

would be awesome to just hit the button and get new upgrades into the distros :D

**Comment by royhills** [comment]
Absolutely agree.  There have been a few bug fixes and some significant libpcap API changes since the last release.

I'm planning to tag 1.9.6 when I've tested the latest changes to support libpcap 1.9.1 on the main operating systems.

There's probably been enough changes since 1.9 to warrant releasing 1.10, but to do that I'll want to do some more thorough testing including testing on a recent version of MacOS X.

**Comment by royhills** [comment]
This has become more urgent with the changes made in libpcap 1.9.1 which were incompatible with arp-scan 1.9.5 and earlier.  See issue #42 

Following the resolution of this issue, point release 1.9.6. has been tagged and point release 1.9.7 from commit 7f372c6 is feature-frozen for the next release.

**Comment by royhills** [comment]
Tag 1.9.7 is release candidate for 1.10.  Tested on:

Debian Linux "Jessie" and "Buster" x64
Arch Linux rolling x64
FreeBSD 12.0 amd64
OpenBSD 6.5 amd64
NetBSD 8.1 amd64
Dragonfly BSD 5.6.2 amd64
Solaris 10 x86
MacOS Mojave 10.14.6 (compile only)

**Comment by royhills** [comment]
Git tags 1.9.7 and 1.9.8 have been released now with 1.9.9 in development. Most of the requested features have been added and reported bugs fixed, so the plan is to release 1.10 when 1.9.9 has completed testing.

**Comment by royhills** [comment]
Version 1.10.0 finally released. (was originally going to be 1.9.9 but changed sue to significant changes).
