### ISSUE TITLE
arp-scan returning entries from other vlan.

### ISSUE THREAD

**Issue by alphabet5** [royhills/arp-scan#65]
Example

```bash
sudo arp-scan --interface=ens160 --vlan=1 192.168.1.20 --arpspa=0.0.0.0
Interface: ens160, type: EN10MB, MAC: 00:0c:29:93:f0:c3, IPv4: (none)
Starting arp-scan 1.9.7 with 1 hosts (https://github.com/royhills/arp-scan)
192.168.1.20	00:50:56:9b:6d:c6	VMware, Inc. (802.1Q VLAN=10)

7 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9.7: 1 hosts scanned in 0.303 seconds (3.30 hosts/sec). 1 responded
```

With a pcap, it appears the arp request isn't honoring the --arpspa flag and is shows up as `Who has 192.168.1.20 Tell 192.168.1.234` instead of `Who has 192.168.1.20? (ARP Probe)`

In the above, 1.234 is assigned to vlan.10@ens160 / vlan tagged interface.

**Comment by royhills** [comment]
This sounds like it could be proxy ARP.  Some operating systems (e.g. Linux) will return ARP responses for IP addresses on other interfaces.  There are some details here:

http://www.royhills.co.uk/wiki/index.php/Arp-scan_User_Guide#Other_Techniques

Could this be what you're seeing?

**Comment by alphabet5** [comment]
@royhills thanks for the response. 

I don't believe it's proxy ARP. This specific machine is Ubuntu (20.04) for reference.

Proxy arp seems to be disabled on all interfaces. (I think)

```text
user@startup:~$ cat /proc/sys/net/ipv4/conf/ens160/proxy_arp
0
user@startup:~$ cat /proc/sys/net/ipv4/conf/vlan.10/proxy_arp
0
user@startup:~$ cat /proc/sys/net/ipv4/conf/all/proxy_arp
0
```

The weird thing is this isn't seen every time. It's been 1/5 -> 1/20 arp-scans it will return the entry. The mac returned is the vmware nic, and not a gateway address.

I'm thinking what is happening is that an ARP request is sent out by another process on this host, and arp-scan captures the reply and includes it in the output. I'm not sure how to verify that, but I'm thinking it's not an issue with arp-scan so I'm closing this issue.

**Comment by royhills** [comment]
The ARP packet doesn't contain an ID field that can be used to match up requests and responses, so it's possible that arp-scan might display results from other ARP responses.  What arp-scan does is:

1. Sets a pcap filter to capture ARP unicast responses that are directed to the sender hardware address (SHA). The default pcap filter string is defined here:

```
/*
 *      The filter string selects packets addressed to the ARP source address
 *      that are Ethernet-II ARP packets, 802.3 LLC/SNAP ARP packets,
 *      802.1Q tagged ARP packets or 802.1Q tagged 802.3 LLC/SNAP ARP packets.
 */
      filter_string=make_message("ether dst %.2x:%.2x:%.2x:%.2x:%.2x:%.2x and "
                                 "(arp or (ether[14:4]=0xaaaa0300 and "
                                 "ether[20:2]=0x0806) or (ether[12:2]=0x8100 "
                                 "and ether[16:2]=0x0806) or "
                                 "(ether[12:2]=0x8100 and "
                                 "ether[18:4]=0xaaaa0300 and "
                                 "ether[24:2]=0x0806))",
                                 arp_sha[0], arp_sha[1],
                                 arp_sha[2], arp_sha[3],
                                 arp_sha[4], arp_sha[5]);
```

2. Received packets that pass the pcap filter get the following checks performed:

a) Is the packet large enough to be a valid ARP response?  If not print "%d byte packet too short to decode\n" and ignore the packet.
b) Does the source IP address in the ARP packet match one of the IP addresses on the list of hosts?  If so display the packet, otherwise print "---\tIgnoring %d bytes from unknown host %s".

So it's possible for an unrelated ARP response to cause arp-scan to print a packet decode, although I've never seen this behaviour myself.
